# Generated by Django 3.1.5 on 2021-02-21 14:05

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('text', models.CharField(blank=True, max_length=2000)),
                ('materials', models.CharField(blank=True, max_length=2000)),
                ('exp', models.IntegerField(default=100)),
                ('slug', models.SlugField(default='123', unique=True)),
                (
                'creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.CharField(default=' ', max_length=1000)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=1000)),
                ('summary', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('start', models.CharField(default='2021-02-23T09:00:00-07:00', max_length=100)),
                ('end', models.CharField(default='2021-02-23T09:00:00-07:00', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
