# Generated by Django 3.1.5 on 2021-02-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(
                choices=[(0, 'Мероприятие'), (1, 'Прием лекарств'), (2, 'Видео тест'), (3, 'Отправка фотографии'),
                         (4, 'Опрос')], default=0),
        ),
    ]
