# Generated by Django 3.1.5 on 2021-02-21 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnostic', '0003_datarecording'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField(default=0)),
                ('activity', models.CharField(max_length=1000)),
                ('standing', models.FloatField(default=0.5)),
                ('sitting', models.FloatField(default=0.1)),
                ('liing', models.FloatField(default=0.1)),
                ('upstairs', models.FloatField(default=0.1)),
                ('downstairs', models.FloatField(default=0.1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
