# Generated by Django 3.1.5 on 2021-04-01 08:36

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnostic', '0006_auto_20210324_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarecording',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='datarecording',
            name='name',
            field=models.CharField(default='File', max_length=100),
        ),
    ]
