# Generated by Django 3.1.5 on 2021-04-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0004_auto_20210407_1303'),
        ('diagnostic', '0010_event_isdone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=1000)),
                ('summary', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('day_delta', models.IntegerField(default=2)),
                ('event_type', models.IntegerField(
                    choices=[(0, 'Мероприятие'), (1, 'Прием лекарств'), (2, 'Видео тест'), (3, 'Отправка фотографии'),
                             (4, 'Опрос')], default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
    ]
