# Generated by Django 3.1.5 on 2021-05-11 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0004_auto_20210407_1303'),
        ('diagnostic', '0013_auto_20210425_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartShedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_interval', models.IntegerField(
                    choices=[(0, 'Ежедневно'), (1, 'Раз в неделю'), (2, 'Раз в месяц'), (3, 'Раз в квартал')],
                    default=0)),
                ('description', models.TextField(default=' ', max_length=1000)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
    ]
