# Generated by Django 3.1.5 on 2021-05-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnostic', '0015_messageshedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageshedule',
            name='day_delta',
            field=models.IntegerField(default=0),
        ),
    ]
