# Generated by Django 3.1.5 on 2021-05-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnostic', '0016_messageshedule_day_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageshedule',
            name='description',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
