# Generated by Django 3.1.5 on 2021-05-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnostic', '0017_messageshedule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='messageshedule',
            name='description',
            field=models.CharField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='messageshedule',
            name='location',
            field=models.CharField(default=' ', max_length=2000),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='location',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='startshedule',
            name='description',
            field=models.TextField(default=' ', max_length=2000),
        ),
    ]
