# Generated by Django 3.2.4 on 2021-06-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnostic', '0018_auto_20210516_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
