# Generated by Django 3.1.5 on 2021-07-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnostic', '0021_datarecording_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(
                choices=[(0, 'Документ'), (1, 'Графический тест'), (2, 'Видеотест'), (3, 'Фототест'), (4, 'Опрос')],
                default=0),
        ),
        migrations.AlterField(
            model_name='messageshedule',
            name='typo',
            field=models.IntegerField(
                choices=[(0, 'Документ'), (1, 'Графический тест'), (2, 'Видеотест'), (3, 'Фототест'), (4, 'Опрос')]),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='event_type',
            field=models.IntegerField(
                choices=[(0, 'Документ'), (1, 'Графический тест'), (2, 'Видеотест'), (3, 'Фототест'), (4, 'Опрос')],
                default=0),
        ),
    ]
