# Generated by Django 3.1.5 on 2021-09-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnostic', '0022_auto_20210727_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarecording',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to='user_files'),
        ),
    ]
