# Generated by Django 3.1.5 on 2021-09-23 00:01

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnostic', '0023_auto_20210901_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=500, upload_to='user_files')),
                ('name', models.CharField(default='File', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('typo', models.IntegerField(choices=[(0, 'Видео'), (1, 'Фотогафия'), (2, 'Фототест')], default=0)),
                ('mark', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=5000)),
                ('summary', models.CharField(default='', max_length=100)),
                ('start', models.DateTimeField(default=datetime.datetime.now)),
                ('end', models.DateTimeField(default=datetime.datetime.now)),
                ('event_type', models.IntegerField(
                    choices=[(0, 'Оценивание видео'), (1, 'Оценивание фотографии'), (2, 'Оценивание фототеста')],
                    default=0)),
                ('isDone', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.mediarecording')),
            ],
        ),
    ]
