# Generated by Django 3.1.5 on 2021-10-04 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0038_auto_20210928_0104'),
        ('diagnostic', '0025_auto_20211004_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorevent',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patient',
                                    to='lk.userprofile'),
        ),
    ]
