# Generated by Django 3.1.5 on 2021-12-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnostic', '0030_mediarecording_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.IntegerField(
                choices=[(0, 'Документ'), (1, 'Графический тест'), (2, 'Видеотест'), (3, 'Фототест'), (4, 'Опрос'),
                         (5, 'Игра')], default=0),
        ),
        migrations.AlterField(
            model_name='messageshedule',
            name='typo',
            field=models.IntegerField(
                choices=[(0, 'Документ'), (1, 'Графический тест'), (2, 'Видеотест'), (3, 'Фототест'), (4, 'Опрос'),
                         (5, 'Игра')]),
        ),
        migrations.AlterField(
            model_name='startevent',
            name='event_type',
            field=models.IntegerField(
                choices=[(0, 'Документ'), (1, 'Графический тест'), (2, 'Видеотест'), (3, 'Фототест'), (4, 'Опрос'),
                         (5, 'Игра')], default=0),
        ),
    ]
