# Generated by Django 3.1.5 on 2021-12-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnostic', '0031_auto_20211205_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorevent',
            name='r0',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='doctorevent',
            name='r1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='doctorevent',
            name='r2',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='doctorevent',
            name='r3',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='doctorevent',
            name='r4',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='mediarecording',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='messageshedule',
            name='r0',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='messageshedule',
            name='r1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='messageshedule',
            name='r2',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='messageshedule',
            name='r3',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='messageshedule',
            name='r4',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
