# Generated by Django 3.2.4 on 2021-12-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnostic', '0033_mediarecording_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='text_r0',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='event',
            name='text_r1',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='event',
            name='text_r2',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='event',
            name='text_r3',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='event',
            name='text_r4',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
