# Generated by Django 3.2.4 on 2021-12-14 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('diagnostic', '0034_auto_20211214_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediarecording',
            name='event_id',
            field=models.ForeignKey(default=2111, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.event'),
        ),
    ]
