# Generated by Django 3.1.5 on 2021-08-31 23:55

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('info', models.TextField(blank=True, max_length=1000)),
                ('typo', models.IntegerField(
                    choices=[(0, 'Таблетка'), (1, 'Капсула'), (2, 'Спрей'), (3, 'Мазь'), (4, 'Пластырь'), (5, 'Укол')],
                    default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PillsReseter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='AssignedPill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_out', models.DateField(null=True)),
                ('is_taken', models.BooleanField(default=True)),
                ('extra', models.CharField(blank=True, default='', max_length=500)),
                ('dosege', models.CharField(default='', max_length=500)),
                ('time', models.TextField(default='', max_length=1000)),
                ('time_taken', models.TextField(default='', max_length=1000)),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pills.pill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
