# Generated by Django 3.1.5 on 2021-05-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pill',
            old_name='time',
            new_name='time1',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='end',
        ),
        migrations.AddField(
            model_name='pill',
            name='is_taken',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='time2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='time3',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='time4',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='time5',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='time_out',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pill',
            name='typo',
            field=models.IntegerField(
                choices=[(0, 'Таблетка'), (1, 'Капсула'), (2, 'Спрей'), (3, 'Мазь'), (4, 'Пластырь'), (5, 'Укол')],
                default=1),
        ),
        migrations.AlterField(
            model_name='pill',
            name='extra',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pill',
            name='info',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
