# Generated by Django 3.1.5 on 2021-05-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pills', '0002_auto_20210506_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill',
            name='time1',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='time3',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='time4',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='time5',
        ),
        migrations.AddField(
            model_name='pill',
            name='time',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
