# Generated by Django 3.1.5 on 2021-05-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pills', '0004_auto_20210506_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill',
            name='dosege',
        ),
        migrations.RemoveField(
            model_name='pill',
            name='extra',
        ),
        migrations.AddField(
            model_name='assignedpill',
            name='dosege',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='assignedpill',
            name='extra',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
