# Generated by Django 3.1.5 on 2021-05-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pills', '0005_auto_20210507_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pill',
            name='time',
        ),
        migrations.AddField(
            model_name='assignedpill',
            name='time',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
