# Generated by Django 3.1.5 on 2021-05-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pills', '0006_auto_20210507_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedpill',
            name='time_taken',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
