# Generated by Django 3.2.4 on 2021-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pills', '0007_assignedpill_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedpill',
            name='time_out',
            field=models.DateField(null=True),
        ),
    ]
