# Generated by Django 3.1.5 on 2021-07-19 18:32

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pills', '0010_auto_20210719_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pillsreseter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
