# Generated by Django 2.2.17 on 2021-01-26 21:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('text', models.CharField(blank=True, max_length=2000)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(upload_to='news')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('vorname', models.CharField(blank=True, max_length=50)),
                ('fathername', models.CharField(blank=True, max_length=50)),
                ('gender', models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')], default=0)),
                ('age', models.DateField(default=datetime.date(2000, 1, 1))),
                ('status', models.IntegerField(choices=[(0, 'Врач'), (1, 'Пациент'), (2, 'Тестировщик'), (3, 'Исследователь')], default=0)),
                ('exp', models.IntegerField(default=0)),
                ('isFull', models.BooleanField(default=False)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(null=True)),
                ('avatar', models.ImageField(default='lk/static/images/noimg.jpg', upload_to='avatars')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('text', models.CharField(blank=True, max_length=2000)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
