# Generated by Django 2.2.17 on 2021-01-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0002_auto_20201031_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='lk/static/images/noimg.jpg', upload_to='avatars'),
        ),
    ]
