# Generated by Django 3.1.5 on 2021-01-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0002_auto_20201031_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='lk/static/images/noimg.jpg', upload_to='avatars'),
        ),
    ]
