# Generated by Django 3.1.5 on 2021-02-21 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0003_auto_20210127_1055'),
        ('lk', '0003_auto_20210122_1316'),
    ]

    operations = [
    ]
