# Generated by Django 3.1.5 on 2021-04-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0004_merge_20210221_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='send_push',
            field=models.BooleanField(default=True),
        ),
    ]
