# Generated by Django 3.1.5 on 2021-04-04 13:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0005_userprofile_send_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='parkinson',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
