# Generated by Django 3.1.5 on 2021-05-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0006_userprofile_parkinson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryrecording',
            name='header',
        ),
        migrations.AddField(
            model_name='diaryrecording',
            name='brake',
            field=models.IntegerField(
                choices=[(0, 'Голова'), (1, 'Шея'), (2, 'Туловище'), (3, 'Правая рука'), (4, 'Левая рука'),
                         (5, 'Правая нога'), (6, 'Левая нога')], default=0),
        ),
        migrations.AddField(
            model_name='diaryrecording',
            name='stimulators',
            field=models.IntegerField(
                choices=[(0, 'Medtronic Aktiva PC'), (1, 'Medtronic Aktiva RC'), (2, 'Abbot Infiniti'),
                         (3, 'Abbot Brio'), (4, 'Boston Vercise PC'), (5, 'Boston Vercise')], default=0),
        ),
        migrations.AddField(
            model_name='diaryrecording',
            name='tremor',
            field=models.IntegerField(
                choices=[(0, 'Голова'), (1, 'Шея'), (2, 'Туловище'), (3, 'Правая рука'), (4, 'Левая рука'),
                         (5, 'Правая нога'), (6, 'Левая нога')], default=0),
        ),
    ]
