# Generated by Django 3.1.5 on 2021-05-10 19:28

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0007_auto_20210510_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryrecording',
            name='brake',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[(0, 'Голова'), (1, 'Шея'), (2, 'Туловище'), (3, 'Правая рука'), (4, 'Левая рука'),
                         (5, 'Правая нога'), (6, 'Левая нога')], default=0, max_length=13),
        ),
        migrations.AlterField(
            model_name='diaryrecording',
            name='tremor',
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[(0, 'Голова'), (1, 'Шея'), (2, 'Туловище'), (3, 'Правая рука'), (4, 'Левая рука'),
                         (5, 'Правая нога'), (6, 'Левая нога')], default=0, max_length=13),
        ),
    ]
