# Generated by Django 3.1.5 on 2021-05-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0008_auto_20210510_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isDiary',
            field=models.BooleanField(default=False),
        ),
    ]
