# Generated by Django 3.1.5 on 2021-05-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0009_userprofile_isdiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isPills',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isSurvey0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isSurvey1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isSurvey2',
            field=models.BooleanField(default=False),
        ),
    ]
