# Generated by Django 3.1.5 on 2021-06-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0012_stepscounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryrecording',
            name='stimulators',
            field=models.IntegerField(
                choices=[(-1, 'Nothing'), (0, 'Medtronic Aktiva PC'), (1, 'Medtronic Aktiva RC'), (2, 'Abbot Infiniti'),
                         (3, 'Abbot Brio'), (4, 'Boston Vercise PC'), (5, 'Boston Vercise')], default=0),
        ),
    ]
