# Generated by Django 3.1.5 on 2021-06-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0013_auto_20210606_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.IntegerField(choices=[(0, 'Центральный регион'), (7, 'Дальневосточный федеральный округ')],
                                      default=0),
        ),
    ]
