# Generated by Django 3.2.4 on 2021-06-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0013_auto_20210606_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timeshift',
            field=models.IntegerField(
                choices=[(-1, ' MSK−1'), (0, 'MSK'), (1, 'MSK+1'), (2, 'MSK+2'), (3, 'MSK+3'), (4, 'MSK+4'),
                         (5, 'MSK+5'), (6, 'MSK+6'), (7, 'MSK+7'), (8, 'MSK+8'), (9, 'MSK+9')], default=0),
        ),
    ]
