# Generated by Django 3.2 on 2021-06-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0014_userprofile_region'),
        ('lk', '0014_userprofile_timeshift'),
    ]

    operations = [
    ]
