# Generated by Django 3.1.5 on 2021-07-02 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0014_userprofile_region'),
        ('lk', '0014_userprofile_timeshift'),
    ]

    operations = [
    ]
