# Generated by Django 3.1.5 on 2021-07-02 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0016_auto_20210702_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='region',
        ),
    ]
