# Generated by Django 3.2 on 2021-07-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0015_merge_20210629_1249'),
        ('lk', '0017_remove_userprofile_region'),
    ]

    operations = [
    ]
