# Generated by Django 3.2 on 2021-07-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0018_merge_20210702_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.IntegerField(choices=[(-1, ' MSK−1'), (0, 'MSK'), (1, 'MSK+1'), (2, 'MSK+2'), (3, 'MSK+3'), (4, 'MSK+4'), (5, 'MSK+5'), (6, 'MSK+6'), (7, 'MSK+7'), (8, 'MSK+8'), (9, 'MSK+9')], null=True),
        ),
    ]
