# Generated by Django 3.2.4 on 2021-07-12 13:09

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lk', '0019_userprofile_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='region',
        ),
        migrations.CreateModel(
            name='HADS_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('depression', models.IntegerField(
                    choices=[(0, '«норма» (отсутствие достоверно выраженных симптомов тревоги и депрессии)'),
                             (1, '«субклинически выраженная тревога / депрессия»'),
                             (2, '«клинически выраженная тревога / депрессия»')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
