# Generated by Django 3.1.5 on 2021-07-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0022_auto_20210712_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reminders',
            field=models.IntegerField(choices=[(0, '1 час'), (1, '3 часа'), (2, '5 часов'), (3, '7 часов')], default=1),
        ),
    ]
