# Generated by Django 3.1.5 on 2021-07-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0024_auto_20210720_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Пациент'), (1, 'Врач'), (2, 'Тестировщик'), (3, 'Исследователь')],
                                      default=0),
        ),
    ]
