# Generated by Django 3.1.5 on 2021-07-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0025_auto_20210720_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Пациент'), (1, 'Врач'), (2, 'Родственник')], default=0),
        ),
    ]
