# Generated by Django 3.1.5 on 2021-07-27 23:12

from django.db import migrations, models

import lk.models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0026_auto_20210727_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.TextField(default=lk.models.generate_pin_string, max_length=10),
        ),
    ]
