# Generated by Django 3.1.5 on 2021-08-13 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lk', '0028_smilestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctor',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
