# Generated by Django 3.1.5 on 2021-09-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0031_shwabstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isStatus',
            field=models.BooleanField(default=False),
        ),
    ]
