# Generated by Django 3.1.5 on 2021-09-01 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lk', '0032_userprofile_isstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='doctor',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
