# Generated by Django 3.1.5 on 2021-09-22 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lk', '0036_updrsstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='relative',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='relative', to=settings.AUTH_USER_MODEL),
        ),
    ]
