# Generated by Django 3.1.5 on 2021-09-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0037_userprofile_relative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memorystatistics',
            old_name='value',
            new_name='pairs',
        ),
        migrations.RenameField(
            model_name='reactionstatistics',
            old_name='value',
            new_name='move',
        ),
        migrations.AddField(
            model_name='memorystatistics',
            name='turn',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reactionstatistics',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
