# Generated by Django 3.1.5 on 2021-10-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0038_auto_20210928_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isPrimaryInfo',
            field=models.BooleanField(default=False),
        ),
    ]
