# Generated by Django 3.1.5 on 2021-10-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lk', '0039_userprofile_isprimaryinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hospital',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isHospitalInfo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.TextField(default=''),
        ),
    ]
