# Generated by Django 3.1.5 on 2021-04-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=1000),
        ),
    ]
