# Generated by Django 3.1.5 on 2021-04-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0003_surveyanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='answers',
            field=models.ManyToManyField(blank=True, to='survey.Answer'),
        ),
    ]
