# Generated by Django 3.1.5 on 2021-06-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0005_question_extra_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='lk/static/images/noimg.jpg', upload_to='surveys'),
        ),
    ]
