# Generated by Django 3.1.5 on 2021-09-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0006_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswer',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to='user_surveys'),
        ),
    ]
