# Generated by Django 3.1.5 on 2021-10-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0007_auto_20210901_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='typo',
            field=models.IntegerField(
                choices=[(0, 'RADIO'), (1, 'TEXT'), (2, 'RADIO+TEXT'), (2, 'DATE'), (3, 'NUANCES')], default=1),
        ),
    ]
