# Generated by Django 3.1.5 on 2021-10-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0008_auto_20211016_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='typo',
            field=models.IntegerField(
                choices=[(0, 'RADIO'), (1, 'TEXT'), (2, 'RADIO+TEXT'), (3, 'DATE'), (4, 'NUANCES'), (5, 'AVATAR')],
                default=1),
        ),
    ]
