# Generated by Django 3.1.5 on 2021-12-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0009_auto_20211017_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='typo',
            field=models.IntegerField(
                choices=[(0, 'RADIO'), (1, 'TEXT'), (2, 'RADIO+TEXT'), (3, 'DATE'), (4, 'NUANCES'), (5, 'AVATAR'),
                         (6, 'TIME')], default=1),
        ),
    ]
