# Generated by Django 3.1.5 on 2021-12-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0010_auto_20211205_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
