# Generated by Django 3.1.5 on 2021-12-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('survey', '0012_answer_typo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='typo',
            field=models.IntegerField(
                choices=[(0, 'RADIO'), (1, 'TEXT'), (2, 'RADIO+TEXT'), (3, 'DATE'), (4, 'NUANCES'), (5, 'AVATAR'),
                         (6, 'TIME'), (7, 'PERCENT')], default=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='typo',
            field=models.IntegerField(
                choices=[(0, 'RADIO'), (1, 'TEXT'), (2, 'RADIO+TEXT'), (3, 'DATE'), (4, 'NUANCES'), (5, 'AVATAR'),
                         (6, 'TIME'), (7, 'PERCENT')], default=1),
        ),
    ]
