# Generated by Django 3.1.5 on 2021-04-25 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0004_auto_20210407_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyShedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_interval', models.IntegerField(
                    choices=[(0, 'Ежедневно'), (1, 'Раз в неделю'), (2, 'Раз в месяц'), (3, 'Раз в квартал')],
                    default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
