# Generated by Django 3.1.5 on 2021-05-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sheduling', '0002_messagesurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesurvey',
            name='forall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surveyshedule',
            name='forall',
            field=models.BooleanField(default=False),
        ),
    ]
