# Generated by Django 3.1.5 on 2021-05-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sheduling', '0003_auto_20210511_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesurvey',
            name='location',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
