# Generated by Django 3.1.5 on 2021-05-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sheduling', '0004_messagesurvey_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesurvey',
            name='day_delta',
            field=models.IntegerField(default=0),
        ),
    ]
