# Generated by Django 3.1.5 on 2021-05-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sheduling', '0005_messagesurvey_day_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesurvey',
            name='location',
            field=models.CharField(default=' ', max_length=2000),
        ),
    ]
