# Generated by Django 3.1.5 on 2021-12-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sheduling', '0006_auto_20210516_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesurvey',
            name='typo',
            field=models.IntegerField(
                choices=[(0, 'Мероприятие'), (1, 'Прием лекарств'), (2, 'Видео тест'), (3, 'Отправка фотографии'),
                         (4, 'Опрос'), (5, 'Игра')]),
        ),
    ]
