# Generated by Django 3.2.4 on 2021-12-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0033_mediarecording_event_id'),
        ('sheduling', '0007_auto_20211205_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesurvey',
            name='messageShedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diagnostic.messageshedule'),
        ),
    ]
