# Generated by Django 3.1.5 on 2021-05-10 21:17

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video_proc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=50)),
                ('text', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoCompetitionRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.FileField(blank=True, upload_to='user_photos')),
                ('trajectory', models.TextField(default='')),
                ('recognition', models.FileField(blank=True, upload_to='user_photos_recogned')),
                ('recognized', models.BooleanField(default=False)),
                ('competition',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_proc.photocompetition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
